package ventana;

/**
 *
 * @author ismal
 */
public class dialogo extends javax.swing.JDialog {

    private String texto;
    
    public void setDatos(String texto, int nLabel){
        /*
        nLabel == 1 -> nombre;
        nLabel == 2 -> telefono;
        nLabel == 3 -> fecha;
        nLabel == 4 -> tipoCocina;
        nLabel == 5 -> nPersonas;
        nLabel == 6 -> tipoReserva;
        nLabel == 7 -> nJornadas;
        nLabel == 8 -> nHabitaciones;
        */
        this.texto = texto;
        switch (nLabel) {
            case 1:
                nombre.setText(texto);
                break;
            case 2:
                telefono.setText(texto);
                break;
            case 3:
                fecha.setText(texto);                
                break;
            case 4:
                tipoCocina.setText(texto);  
                break;
            case 5:
                nPersonas.setText(texto);  
                break;
            case 6:
                tipoReserva.setText(texto);  
                break;
            case 7:
                nJornadas.setText(texto);  
                break;
            case 8:
                nHabitaciones.setText(texto);  
                break;                
        }
    }
    
    /**
     * Creates new form dialogo
     */
    public dialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        telefono = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        tipoCocina = new javax.swing.JLabel();
        tipoReserva = new javax.swing.JLabel();
        nPersonas = new javax.swing.JLabel();
        nJornadas = new javax.swing.JLabel();
        nHabitaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reserva");
        setSize(new java.awt.Dimension(600, 400));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        telefono.setText("Teléfono");
        telefono.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        fecha.setText("Fecha");
        fecha.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nombre.setText("Nombre");
        nombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tipoCocina.setText("Tipo Cocina");
        tipoCocina.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tipoReserva.setText("Tipo");
        tipoReserva.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nPersonas.setText("Número Personas");
        nPersonas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nJornadas.setText("Número Jornadas");
        nJornadas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nHabitaciones.setText("Número Habitaciones");
        nHabitaciones.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habana.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(fecha)
                    .addComponent(telefono)
                    .addComponent(tipoCocina)
                    .addComponent(nHabitaciones)
                    .addComponent(nJornadas)
                    .addComponent(nPersonas)
                    .addComponent(tipoReserva))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoCocina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nPersonas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nJornadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nHabitaciones))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogo dialog = new dialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nHabitaciones;
    private javax.swing.JLabel nJornadas;
    private javax.swing.JLabel nPersonas;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel tipoCocina;
    private javax.swing.JLabel tipoReserva;
    // End of variables declaration//GEN-END:variables
}
